# Generated by Django 4.2.19 on 2025-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_childprofile_achievements_childprofile_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='direction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
