# Generated by Django 4.2.19 on 2025-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
