# Generated by Django 4.2.19 on 2025-03-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0003_childprofile_achievements_childprofile_parent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reward', models.CharField(max_length=200)),
                ('how_to_unlock', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('unlock_date', models.DateField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_achievements', to='teachers.childprofile')),
            ],
        ),
    ]
